build:
  environment:
    php:
      version: "8.0"
  nodes:
    coverage:
      tests:
        override:
          - command: ./vendor/bin/phpunit --coverage-clover phpunit.coverage.xml --verbose --filter coredump
            coverage:
              file: phpunit.coverage.xml
              format: clover
    analysis:
      tests:
        override:
          - php-scrutinizer-run