build:
  environment:
    php:
      version: "8.0"
  nodes:
    coverage:
      tests:
        override:
          - command: 
            coverage:
              file: phpunit.coverage.xml
              format: clover
    analysis:
      tests:
        override:
          - php-scrutinizer-run